dist: bionic
language: clojure
lein: 2.9.10
jobs:
  include:
    # The OpenJDK versions used by Travis are pretty old, which causes
    # problems with some of the tests. This pulls in a semi-recent version
    # from the Ubuntu repos.
    - name: jdk8
      before_install:
        - sudo rm -rf /usr/local/lib/jvm/
        - sudo rm -rf /usr/lib/jvm/openjdk-8
        - sudo apt-get install -y openjdk-8-jdk-headless
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
      script:
        - lein with-profile dev test
    #- # same as previous stage
    #  script: lein with-profile fips test
    #  jdk: openjdk8
    - name: jdk11
      before_install:
        - sudo rm -rf /usr/local/lib/jvm/
        - sudo rm -rf /usr/lib/jvm/openjdk-11
        - sudo apt-get install -y openjdk-11-jdk-headless
        - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
      script:
        - lein with-profile dev test
    #- # same as previous stage
    #  script: lein with-profile fips test
    #  jdk: openjdk11
sudo: false
# Java needs to be able to resolve its hostname when doing integration style
# tests, which it cannot do in certain cases with travis-ci.  If we need the
# runtime/container to be able to resolve its own hostname we need to use
# either the `hostname` or `hosts` "addon" for travis.  Since we don't care
# what the hostname is, here we just give it a garbage name based on the name
# of the project.
addons:
  hostname: cljhttpclient
notifications:
  email: false
